In [1]:
import numpy as np

In [11]:
a=open("grid10.txt")
l=np.zeros((11,11))
j=0
for i in a:
    i=i.replace(" ","")
    i=i.replace("\n","")
    l[j]=list(i)
    j=j+1
print(l)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 2. 0. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 0. 3. 1. 0. 1.]
 [1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [68]:
n=11
v=np.zeros((n,n))
V=np.zeros((n,n))
for k in range(1000):
    for i in range(1,n-1):
        for j in range(1,n-1):
            if l[i][j]==1 or l[i][j]==3:
                continue
            g=np.array([v[i+1][j],v[i-1][j],v[i][j+1],v[i][j-1]])
            gd={1:v[i+1][j],2:v[i-1][j],3:v[i][j+1],4:v[i][j-1]}
            if l[i+1][j]==1:
                del gd[1]
            if l[i-1][j]==1:
                del gd[2]
            if l[i][j+1]==1:
                del gd[3]
            if l[i][j-1]==1:
                del gd[4]
            V[i][j]=np.mean(list(gd.values()))-1
    v=V
    V=np.zeros((n,n))
print(v.round(2))

[[   0.      0.      0.      0.      0.      0.      0.      0.      0.
     0.      0.  ]
 [   0.   -680.68 -693.14 -704.49 -714.75 -723.93 -732.06 -739.14 -750.12
  -760.09    0.  ]
 [   0.   -667.09    0.      0.      0.      0.      0.   -733.69    0.
  -769.06    0.  ]
 [   0.   -652.36 -672.02 -690.54 -701.33 -711.03 -719.64 -727.19    0.
  -777.06    0.  ]
 [   0.   -616.21    0.   -696.59    0.      0.      0.      0.      0.
  -784.08    0.  ]
 [   0.   -578.83    0.   -701.53 -703.18 -703.73    0.   -792.04 -791.57
  -790.16    0.  ]
 [   0.   -540.17    0.   -703.18    0.      0.      0.      0.      0.
  -793.42    0.  ]
 [   0.   -500.18    0.   -703.73    0.   -118.24  -60.09    0.      0.
  -795.74    0.  ]
 [   0.   -458.8     0.      0.      0.   -174.51    0.      0.      0.
  -797.13    0.  ]
 [   0.   -415.97 -371.63 -325.73 -278.2  -228.98 -231.6  -232.48    0.
  -797.59    0.  ]
 [   0.      0.      0.      0.      0.      0.      0.      0.      0.
     0.      0

In [69]:
p=np.zeros((n,n))
d1={1:"n",2:"e",3:"w",4:"s"}
for i in range(n):
    for  j in range(n):
        if l[i][j]==1 or l[i][j]==3:
            p[i][j]=0
            continue
        else:
            d={1:v[i-1][j],2:v[i][j+1],3:v[i][j-1],4:v[i+1][j]}
            if l[i-1][j]==1:
                d[1]=-100000
            if l[i][j+1]==1:
                d[2]=-100000
            if l[i][j-1]==1:
                d[3]=-100000
            if l[i+1][j]==1:
                d[4]=-100000
            p[i][j]=max(d, key = d.get)
print(p)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 3. 3. 3. 3. 3. 3. 3. 3. 0.]
 [0. 4. 0. 0. 0. 0. 0. 4. 0. 1. 0.]
 [0. 4. 3. 3. 3. 3. 3. 3. 0. 1. 0.]
 [0. 4. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 4. 0. 1. 3. 3. 0. 2. 2. 1. 0.]
 [0. 4. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 4. 0. 1. 0. 2. 2. 0. 0. 1. 0.]
 [0. 4. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 2. 2. 2. 2. 1. 3. 3. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [70]:
si,sj=np.where(l==2)
i=int(si)
j=int(sj)
print(l,i,j)
while l[i][j]!=3:
    a=d1[p[i][j]]
    print(a,end=" ")
    if a=="n":
        i=i-1
    if a=="w":
        j=j-1
    if a=="e":
        j=j+1
    if a=="s":
        i=i+1

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 2. 0. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 0. 3. 1. 0. 1.]
 [1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 1 7
w w w w w w s s s s s s s s e e e e n n e e 